<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <RuntimeIdentifiers>win-x64;win-x86</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <Content Update="wwwroot/uploads/**">
		  <CopyToPublishDirectory>Never</CopyToPublishDirectory>
	  </Content>
	  <Content Update="wwwroot/3dModel/**">
		  <CopyToPublishDirectory>Never</CopyToPublishDirectory>
	  </Content>
	  <Content Update="wwwroot/3dpurchased/**">
		  <CopyToPublishDirectory>Never</CopyToPublishDirectory>
	  </Content>
	  <Content Update="wwwroot/models/**">
		  <CopyToPublishDirectory>Never</CopyToPublishDirectory>
	  </Content>
  </ItemGroup>

</Project>
